# Site settings
title: Michael W Eastwood
email: michael.w.eastwood@gmail.com
description: "The personal website of Michael W Eastwood."
baseurl: ""
url: "http://mweastwood.info"
github_username: mweastwood
current_institution: California Institute of Technology

# Build settings
markdown: kramdown
permalink: pretty

